version: "2"

services:
        migrate:
            build: .
            command: ["node", "ace", "migration:run"]

        api:
            build: .
            container_name: vetores-endemias-api
            depends_on:
                - migrate
            command: adonis serve          
            ports:
                - "8081:8081"
            volumes:
                - .:/usr/app
